import pytest

from jama_rest_client.dal.parsers.json import ItemTypeJSONParser
from jama_rest_client.model.item_type import ItemType, ItemTypeCategory, ItemTypeFieldTextType, ItemTypeFieldType

from mocks.item_types import ItemTypesMocks, ITEM_TYPES_API_MOCKS
from test_utilities.builders.item_type import ItemTypeBuilder, ItemTypeFieldBuilder

class TestItemTypeJSONParser():

    @pytest.mark.parametrize(
      "item_type_dict, expected_item_type",
      [
        (
            ITEM_TYPES_API_MOCKS[ItemTypesMocks.CASE_1_ELEMENT]['data'][0],
            ItemTypeBuilder().set_id(1)
                             .set_type_key('DummyTypeKey 1')
                             .set_display('DummyDisplay 1')
                             .set_display_plural('DummyDisplayPlural 1')
                             .set_description('DummyDescription 1')
                             .set_image('DummyImage 1')
                             .set_category(ItemTypeCategory.ATTACHMENT)
                             .set_fields(
                                 [
                                     ItemTypeFieldBuilder().set_id(1)
                                                           .set_name('DummyName 1')
                                                           .set_label('DummyLabel 1')
                                                           .set_field_type(ItemTypeFieldType.ACTIONS)
                                                           .set_read_only(True)
                                                           .set_read_only_allow_api_overwrite(False)
                                                           .set_required(False)
                                                           .set_trigger_suspect(False)
                                                           .set_synchronize(False)
                                                           .set_pick_list(1)
                                                           .set_text_type(ItemTypeFieldTextType.ATTACHMENT)
                                                           .set_item_type(1)
                                                           .get_element(),
                                     ItemTypeFieldBuilder().set_id(2)
                                                           .set_name('DummyName 2')
                                                           .set_label('DummyLabel 2')
                                                           .set_field_type(ItemTypeFieldType.BOOLEAN)
                                                           .set_read_only(False)
                                                           .set_read_only_allow_api_overwrite(True)
                                                           .set_required(False)
                                                           .set_trigger_suspect(False)
                                                           .set_synchronize(False)
                                                           .set_pick_list(2)
                                                           .set_text_type(ItemTypeFieldTextType.KEY)
                                                           .set_item_type(2)
                                                           .get_element(),
                                     ItemTypeFieldBuilder().set_id(3)
                                                           .set_name('DummyName 3')
                                                           .set_label('DummyLabel 3')
                                                           .set_field_type(ItemTypeFieldType.CALCULATED)
                                                           .set_read_only(False)
                                                           .set_read_only_allow_api_overwrite(False)
                                                           .set_required(True)
                                                           .set_trigger_suspect(False)
                                                           .set_synchronize(False)
                                                           .set_pick_list(3)
                                                           .set_text_type(ItemTypeFieldTextType.RICHTEXT)
                                                           .set_item_type(3)
                                                           .get_element(),
                                     ItemTypeFieldBuilder().set_id(4)
                                                           .set_name('DummyName 4')
                                                           .set_label('DummyLabel 4')
                                                           .set_field_type(ItemTypeFieldType.DATE)
                                                           .set_read_only(False)
                                                           .set_read_only_allow_api_overwrite(False)
                                                           .set_required(False)
                                                           .set_trigger_suspect(True)
                                                           .set_synchronize(False)
                                                           .set_pick_list(4)
                                                           .set_text_type(ItemTypeFieldTextType.TEXTAREA)
                                                           .set_item_type(4)
                                                           .get_element(),
                                    ItemTypeFieldBuilder().set_id(5)
                                                          .set_name('DummyName 5')
                                                          .set_label('DummyLabel 5')
                                                          .set_field_type(ItemTypeFieldType.DOCUMENT_TYPE)
                                                          .set_read_only(False)
                                                          .set_read_only_allow_api_overwrite(False)
                                                          .set_required(False)
                                                          .set_trigger_suspect(False)
                                                          .set_synchronize(True)
                                                          .set_pick_list(5)
                                                          .set_text_type(ItemTypeFieldTextType.TEXTAREA)
                                                          .set_item_type(5)
                                                          .get_element(),
                                    ItemTypeFieldBuilder().set_id(6)
                                                          .set_name('DummyName 6')
                                                          .set_label('DummyLabel 6')
                                                          .set_field_type(ItemTypeFieldType.DOCUMENT_TYPE_CATEGORY_ITEM_LOOKUP)
                                                          .set_read_only(False)
                                                          .set_read_only_allow_api_overwrite(False)
                                                          .set_required(False)
                                                          .set_trigger_suspect(True)
                                                          .set_synchronize(False)
                                                          .set_pick_list(6)
                                                          .set_text_type(ItemTypeFieldTextType.TEXTAREA)
                                                          .set_item_type(6)
                                                          .get_element(),
                                    ItemTypeFieldBuilder().set_id(7)
                                                          .set_name('DummyName 7')
                                                          .set_label('DummyLabel 7')
                                                          .set_field_type(ItemTypeFieldType.DOCUMENT_TYPE_ITEM_LOOKUP)
                                                          .set_read_only(False)
                                                          .set_read_only_allow_api_overwrite(False)
                                                          .set_required(False)
                                                          .set_trigger_suspect(True)
                                                          .set_synchronize(False)
                                                          .set_pick_list(7)
                                                          .set_text_type(ItemTypeFieldTextType.TEXTAREA)
                                                          .set_item_type(7)
                                                          .get_element(),
                                    ItemTypeFieldBuilder().set_id(8)
                                                          .set_name('DummyName 8')
                                                          .set_label('DummyLabel 8')
                                                          .set_field_type(ItemTypeFieldType.GROUP)
                                                          .set_read_only(False)
                                                          .set_read_only_allow_api_overwrite(False)
                                                          .set_required(False)
                                                          .set_trigger_suspect(True)
                                                          .set_synchronize(False)
                                                          .set_pick_list(8)
                                                          .set_text_type(ItemTypeFieldTextType.TEXTAREA)
                                                          .set_item_type(8)
                                                          .get_element(),
                                    ItemTypeFieldBuilder().set_id(9)
                                                          .set_name('DummyName 9')
                                                          .set_label('DummyLabel 9')
                                                          .set_field_type(ItemTypeFieldType.INTEGER)
                                                          .set_read_only(False)
                                                          .set_read_only_allow_api_overwrite(False)
                                                          .set_required(False)
                                                          .set_trigger_suspect(True)
                                                          .set_synchronize(False)
                                                          .set_pick_list(9)
                                                          .set_text_type(ItemTypeFieldTextType.TEXTAREA)
                                                          .set_item_type(9)
                                                          .get_element(),
                                    ItemTypeFieldBuilder().set_id(10)
                                                          .set_name('DummyName 10')
                                                          .set_label('DummyLabel 10')
                                                          .set_field_type(ItemTypeFieldType.LOOKUP)
                                                          .set_read_only(False)
                                                          .set_read_only_allow_api_overwrite(False)
                                                          .set_required(False)
                                                          .set_trigger_suspect(True)
                                                          .set_synchronize(False)
                                                          .set_pick_list(10)
                                                          .set_text_type(ItemTypeFieldTextType.TEXTAREA)
                                                          .set_item_type(10)
                                                          .get_element(),
                                    ItemTypeFieldBuilder().set_id(11)
                                                          .set_name('DummyName 11')
                                                          .set_label('DummyLabel 11')
                                                          .set_field_type(ItemTypeFieldType.MULTI_LOOKUP)
                                                          .set_read_only(False)
                                                          .set_read_only_allow_api_overwrite(False)
                                                          .set_required(False)
                                                          .set_trigger_suspect(True)
                                                          .set_synchronize(False)
                                                          .set_pick_list(11)
                                                          .set_text_type(ItemTypeFieldTextType.TEXTAREA)
                                                          .set_item_type(11)
                                                          .get_element(),
                                    ItemTypeFieldBuilder().set_id(12)
                                                          .set_name('DummyName 12')
                                                          .set_label('DummyLabel 12')
                                                          .set_field_type(ItemTypeFieldType.PROJECT)
                                                          .set_read_only(False)
                                                          .set_read_only_allow_api_overwrite(False)
                                                          .set_required(False)
                                                          .set_trigger_suspect(True)
                                                          .set_synchronize(False)
                                                          .set_pick_list(12)
                                                          .set_text_type(ItemTypeFieldTextType.TEXTAREA)
                                                          .set_item_type(12)
                                                          .get_element(),
                                    ItemTypeFieldBuilder().set_id(13)
                                                          .set_name('DummyName 13')
                                                          .set_label('DummyLabel 13')
                                                          .set_field_type(ItemTypeFieldType.RELATIONSHIP_STATUS)
                                                          .set_read_only(False)
                                                          .set_read_only_allow_api_overwrite(False)
                                                          .set_required(False)
                                                          .set_trigger_suspect(True)
                                                          .set_synchronize(False)
                                                          .set_pick_list(13)
                                                          .set_text_type(ItemTypeFieldTextType.TEXTAREA)
                                                          .set_item_type(13)
                                                          .get_element(),
                                    ItemTypeFieldBuilder().set_id(14)
                                                          .set_name('DummyName 14')
                                                          .set_label('DummyLabel 14')
                                                          .set_field_type(ItemTypeFieldType.RELATIVE_DATE_RANGE)
                                                          .set_read_only(False)
                                                          .set_read_only_allow_api_overwrite(False)
                                                          .set_required(False)
                                                          .set_trigger_suspect(True)
                                                          .set_synchronize(False)
                                                          .set_pick_list(14)
                                                          .set_text_type(ItemTypeFieldTextType.TEXTAREA)
                                                          .set_item_type(14)
                                                          .get_element(),
                                    ItemTypeFieldBuilder().set_id(15)
                                                          .set_name('DummyName 15')
                                                          .set_label('DummyLabel 15')
                                                          .set_field_type(ItemTypeFieldType.RELEASE)
                                                          .set_read_only(False)
                                                          .set_read_only_allow_api_overwrite(False)
                                                          .set_required(False)
                                                          .set_trigger_suspect(True)
                                                          .set_synchronize(False)
                                                          .set_pick_list(15)
                                                          .set_text_type(ItemTypeFieldTextType.TEXTAREA)
                                                          .set_item_type(15)
                                                          .get_element(),
                                    ItemTypeFieldBuilder().set_id(16)
                                                          .set_name('DummyName 16')
                                                          .set_label('DummyLabel 16')
                                                          .set_field_type(ItemTypeFieldType.ROLLUP)
                                                          .set_read_only(False)
                                                          .set_read_only_allow_api_overwrite(False)
                                                          .set_required(False)
                                                          .set_trigger_suspect(True)
                                                          .set_synchronize(False)
                                                          .set_pick_list(16)
                                                          .set_text_type(ItemTypeFieldTextType.TEXTAREA)
                                                          .set_item_type(16)
                                                          .get_element(),
                                    ItemTypeFieldBuilder().set_id(17)
                                                          .set_name('DummyName 17')
                                                          .set_label('DummyLabel 17')
                                                          .set_field_type(ItemTypeFieldType.STEPS)
                                                          .set_read_only(False)
                                                          .set_read_only_allow_api_overwrite(False)
                                                          .set_required(False)
                                                          .set_trigger_suspect(True)
                                                          .set_synchronize(False)
                                                          .set_pick_list(17)
                                                          .set_text_type(ItemTypeFieldTextType.TEXTAREA)
                                                          .set_item_type(17)
                                                          .get_element(),
                                    ItemTypeFieldBuilder().set_id(18)
                                                          .set_name('DummyName 18')
                                                          .set_label('DummyLabel 18')
                                                          .set_field_type(ItemTypeFieldType.STRING)
                                                          .set_read_only(False)
                                                          .set_read_only_allow_api_overwrite(False)
                                                          .set_required(False)
                                                          .set_trigger_suspect(True)
                                                          .set_synchronize(False)
                                                          .set_pick_list(18)
                                                          .set_text_type(ItemTypeFieldTextType.TEXTAREA)
                                                          .set_item_type(18)
                                                          .get_element(),
                                    ItemTypeFieldBuilder().set_id(19)
                                                          .set_name('DummyName 19')
                                                          .set_label('DummyLabel 19')
                                                          .set_field_type(ItemTypeFieldType.TEST_CASE_STATUS)
                                                          .set_read_only(False)
                                                          .set_read_only_allow_api_overwrite(False)
                                                          .set_required(False)
                                                          .set_trigger_suspect(True)
                                                          .set_synchronize(False)
                                                          .set_pick_list(19)
                                                          .set_text_type(ItemTypeFieldTextType.TEXTAREA)
                                                          .set_item_type(19)
                                                          .get_element(),
                                    ItemTypeFieldBuilder().set_id(20)
                                                          .set_name('DummyName 20')
                                                          .set_label('DummyLabel 20')
                                                          .set_field_type(ItemTypeFieldType.TEST_RUN_STATUS)
                                                          .set_read_only(False)
                                                          .set_read_only_allow_api_overwrite(False)
                                                          .set_required(False)
                                                          .set_trigger_suspect(True)
                                                          .set_synchronize(False)
                                                          .set_pick_list(20)
                                                          .set_text_type(ItemTypeFieldTextType.TEXTAREA)
                                                          .set_item_type(20)
                                                          .get_element(),
                                    ItemTypeFieldBuilder().set_id(21)
                                                          .set_name('DummyName 21')
                                                          .set_label('DummyLabel 21')
                                                          .set_field_type(ItemTypeFieldType.TEXT)
                                                          .set_read_only(False)
                                                          .set_read_only_allow_api_overwrite(False)
                                                          .set_required(False)
                                                          .set_trigger_suspect(True)
                                                          .set_synchronize(False)
                                                          .set_pick_list(21)
                                                          .set_text_type(ItemTypeFieldTextType.TEXTAREA)
                                                          .set_item_type(21)
                                                          .get_element(),
                                    ItemTypeFieldBuilder().set_id(22)
                                                          .set_name('DummyName 22')
                                                          .set_label('DummyLabel 22')
                                                          .set_field_type(ItemTypeFieldType.TIME)
                                                          .set_read_only(False)
                                                          .set_read_only_allow_api_overwrite(False)
                                                          .set_required(False)
                                                          .set_trigger_suspect(True)
                                                          .set_synchronize(False)
                                                          .set_pick_list(22)
                                                          .set_text_type(ItemTypeFieldTextType.TEXTAREA)
                                                          .set_item_type(22)
                                                          .get_element(),
                                    ItemTypeFieldBuilder().set_id(23)
                                                          .set_name('DummyName 23')
                                                          .set_label('DummyLabel 23')
                                                          .set_field_type(ItemTypeFieldType.URL_STRING)
                                                          .set_read_only(False)
                                                          .set_read_only_allow_api_overwrite(False)
                                                          .set_required(False)
                                                          .set_trigger_suspect(True)
                                                          .set_synchronize(False)
                                                          .set_pick_list(23)
                                                          .set_text_type(ItemTypeFieldTextType.TEXTAREA)
                                                          .set_item_type(23)
                                                          .get_element(),
                                    ItemTypeFieldBuilder().set_id(24)
                                                          .set_name('DummyName 24')
                                                          .set_label('DummyLabel 24')
                                                          .set_field_type(ItemTypeFieldType.USER)
                                                          .set_read_only(False)
                                                          .set_read_only_allow_api_overwrite(False)
                                                          .set_required(False)
                                                          .set_trigger_suspect(True)
                                                          .set_synchronize(False)
                                                          .set_pick_list(24)
                                                          .set_text_type(ItemTypeFieldTextType.TEXTAREA)
                                                          .set_item_type(24)
                                                          .get_element()
                                 ]
                             )
                             .set_system(False)
                             .get_element()
        ),
        (
            ITEM_TYPES_API_MOCKS[ItemTypesMocks.CASE_1_ELEMENT_CATEGORY_COMPONENT]['data'][0],
            ItemTypeBuilder().set_id(1)
                             .set_type_key('DummyTypeKey 1')
                             .set_display('DummyDisplay 1')
                             .set_display_plural('DummyDisplayPlural 1')
                             .set_description('DummyDescription 1')
                             .set_image('DummyImage 1')
                             .set_category(ItemTypeCategory.COMPONENT)
                             .set_system(True)
                             .get_element()
        ),
        (
            ITEM_TYPES_API_MOCKS[ItemTypesMocks.CASE_1_ELEMENT_CATEGORY_CORE]['data'][0],
            ItemTypeBuilder().set_id(1)
                             .set_type_key('DummyTypeKey 1')
                             .set_display('DummyDisplay 1')
                             .set_display_plural('DummyDisplayPlural 1')
                             .set_description('DummyDescription 1')
                             .set_image('DummyImage 1')
                             .set_category(ItemTypeCategory.CORE)
                             .set_system(True)
                             .get_element()
        ),
        (
            ITEM_TYPES_API_MOCKS[ItemTypesMocks.CASE_1_ELEMENT_CATEGORY_DEFECT]['data'][0],
            ItemTypeBuilder().set_id(1)
                             .set_type_key('DummyTypeKey 1')
                             .set_display('DummyDisplay 1')
                             .set_display_plural('DummyDisplayPlural 1')
                             .set_description('DummyDescription 1')
                             .set_image('DummyImage 1')
                             .set_category(ItemTypeCategory.DEFECT)
                             .set_system(True)
                             .get_element()
        ),
        (
            ITEM_TYPES_API_MOCKS[ItemTypesMocks.CASE_1_ELEMENT_CATEGORY_SECTION]['data'][0],
            ItemTypeBuilder().set_id(1)
                             .set_type_key('DummyTypeKey 1')
                             .set_display('DummyDisplay 1')
                             .set_display_plural('DummyDisplayPlural 1')
                             .set_description('DummyDescription 1')
                             .set_image('DummyImage 1')
                             .set_category(ItemTypeCategory.SECTION)
                             .set_system(True)
                             .get_element()
        ),
        (
            ITEM_TYPES_API_MOCKS[ItemTypesMocks.CASE_1_ELEMENT_CATEGORY_SET]['data'][0],
            ItemTypeBuilder().set_id(1)
                             .set_type_key('DummyTypeKey 1')
                             .set_display('DummyDisplay 1')
                             .set_display_plural('DummyDisplayPlural 1')
                             .set_description('DummyDescription 1')
                             .set_image('DummyImage 1')
                             .set_category(ItemTypeCategory.SET)
                             .set_system(True)
                             .get_element()
        ),
        (
            ITEM_TYPES_API_MOCKS[ItemTypesMocks.CASE_1_ELEMENT_CATEGORY_TEST_CASE]['data'][0],
            ItemTypeBuilder().set_id(1)
                             .set_type_key('DummyTypeKey 1')
                             .set_display('DummyDisplay 1')
                             .set_display_plural('DummyDisplayPlural 1')
                             .set_description('DummyDescription 1')
                             .set_image('DummyImage 1')
                             .set_category(ItemTypeCategory.TEST_CASE)
                             .set_system(True)
                             .get_element()
        ),
        (
            ITEM_TYPES_API_MOCKS[ItemTypesMocks.CASE_1_ELEMENT_CATEGORY_TEST_CYCLE]['data'][0],
            ItemTypeBuilder().set_id(1)
                             .set_type_key('DummyTypeKey 1')
                             .set_display('DummyDisplay 1')
                             .set_display_plural('DummyDisplayPlural 1')
                             .set_description('DummyDescription 1')
                             .set_image('DummyImage 1')
                             .set_category(ItemTypeCategory.TEST_CYCLE)
                             .set_system(True)
                             .get_element()
        ),
        (
            ITEM_TYPES_API_MOCKS[ItemTypesMocks.CASE_1_ELEMENT_CATEGORY_TEST_PLAN]['data'][0],
            ItemTypeBuilder().set_id(1)
                             .set_type_key('DummyTypeKey 1')
                             .set_display('DummyDisplay 1')
                             .set_display_plural('DummyDisplayPlural 1')
                             .set_description('DummyDescription 1')
                             .set_image('DummyImage 1')
                             .set_category(ItemTypeCategory.TEST_PLAN)
                             .set_system(True)
                             .get_element()
        ),
        (
            ITEM_TYPES_API_MOCKS[ItemTypesMocks.CASE_1_ELEMENT_CATEGORY_TEST_RUN]['data'][0],
            ItemTypeBuilder().set_id(1)
                             .set_type_key('DummyTypeKey 1')
                             .set_display('DummyDisplay 1')
                             .set_display_plural('DummyDisplayPlural 1')
                             .set_description('DummyDescription 1')
                             .set_image('DummyImage 1')
                             .set_category(ItemTypeCategory.TEST_RUN)
                             .set_system(True)
                             .get_element()
        ),
        (
            ITEM_TYPES_API_MOCKS[ItemTypesMocks.CASE_1_ELEMENT_CATEGORY_TEXT]['data'][0],
            ItemTypeBuilder().set_id(1)
                             .set_type_key('DummyTypeKey 1')
                             .set_display('DummyDisplay 1')
                             .set_display_plural('DummyDisplayPlural 1')
                             .set_description('DummyDescription 1')
                             .set_image('DummyImage 1')
                             .set_category(ItemTypeCategory.TEXT)
                             .set_system(True)
                             .get_element()
        )
      ]
    )
    def test_validate_happy_path_parse_item_type_returns_expected_value(self, item_type_dict: dict, expected_item_type: ItemType) -> None:
        item_type = ItemTypeJSONParser.parse(item_type_dict)
        assert expected_item_type == item_type

    @pytest.mark.parametrize(
      "item_type_dict, expected_exception",
      [
        (
            ITEM_TYPES_API_MOCKS[ItemTypesMocks.CASE_1_ELEMENT_WRONG_CATEGORY]['data'][0],
            ValueError('ItemType category has an invalid value: DummyCategory')
        ),
        (
            ITEM_TYPES_API_MOCKS[ItemTypesMocks.CASE_1_ELEMENT_WRONG_FIELD_TYPE]['data'][0],
            ValueError('ItemTypeField fieldType has an invalid value: DummyFieldType')
        ),
        (
            ITEM_TYPES_API_MOCKS[ItemTypesMocks.CASE_1_ELEMENT_WRONG_TEXT_TYPE]['data'][0],
            ValueError('ItemTypeField textType has an invalid value: DummyTextType')
        )
      ]
    )
    def test_validate_parse_item_type_raises_exception_when_wrong_value(self, item_type_dict: dict, expected_exception: ValueError) -> None:
        with pytest.raises(ValueError) as value_error_exception:
          ItemTypeJSONParser.parse(item_type_dict)

        assert expected_exception.args == value_error_exception.value.args